# Dependabot configuration file
version: 2
updates:
  # Enable version updates for npm (frontend)
  - package-ecosystem: "npm"
    # Look for package.json and package-lock.json files in the frontend directory
    directory: "/frontend"
    # Check for updates once a week (on Monday)
    schedule:
      interval: "weekly"
      day: "monday"
    # Limit the number of open pull requests to 5
    open-pull-requests-limit: 5
    # Group all minor and patch updates together
    groups:
      dev-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "*eslint*"
      react-dependencies:
        patterns:
          - "react"
          - "react-dom"
          - "react-router*"
    # Assign reviewers to pull requests
    reviewers:
      - "pkhemae"
    # Labels to apply to pull requests
    labels:
      - "dependencies"
      - "npm"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Look for GitHub Actions workflow files in the .github/workflows directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Limit the number of open pull requests to 3
    open-pull-requests-limit: 3
    # Labels to apply to pull requests
    labels:
      - "dependencies"
      - "github-actions"